export enum ErrorCode {
  // INFRA
  INFRA_CONNECTION_REFUSED = 'INFRA_CONNECTION_REFUSED',
  INFRA_TIMEOUT = 'INFRA_TIMEOUT',
  INFRA_NOT_FOUND = 'INFRA_NOT_FOUND',
  INFRA_REDIS_CONFIG = 'INFRA_REDIS_CONFIG',
  // DB
  DB_DUPLICATE_KEY = 'DB_DUPLICATE_KEY',
  DB_NULL_VALUE = 'DB_NULL_VALUE',
  DB_ERROR = 'DB_ERROR',
  // AUTH
  AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED = 'AUTH_UNAUTHORIZED',
  AUTH_FORBIDDEN = 'AUTH_FORBIDDEN',
  AUTH_PROVIDER_ERROR = 'AUTH_PROVIDER_ERROR',
  // COMPLETION
  COMPLETION_TIMEOUT = 'COMPLETION_TIMEOUT',
  COMPLETION_NO_PROVIDER = 'COMPLETION_NO_PROVIDER',
  COMPLETION_QUOTA_EXHAUSTED = 'COMPLETION_QUOTA_EXHAUSTED',
  COMPLETION_RATE_LIMITED = 'COMPLETION_RATE_LIMITED',
  COMPLETION_PROVIDERS_UNAVAILABLE = 'COMPLETION_PROVIDERS_UNAVAILABLE',
  COMPLETION_ALL_FAILED = 'COMPLETION_ALL_FAILED',
  COMPLETION_BAD_REQUEST = 'COMPLETION_BAD_REQUEST',
  // GENERIC
  GENERIC_ERROR = 'GENERIC_ERROR',
}
